/* Citro3DGPU.h - citro3d */

#ifndef CITRO3D_GPU_CITRO3D_H
#define CITRO3D_GPU_CITRO3D_H

#include <Size.h>
#include <GPU.h>

// These headers are generated by the build process
#include <shaders/shader2d.shbin.h>
//#include <shader3d.shbin.h>

class Citro3DGPU : public GPU {
    public:
        Citro3DGPU(Size& screen);
        ~Citro3DGPU();

        void clear();
        void display();

        void alloc_texture(Texture& texture, const uint8_t* data, const size_t data_size);
        void free_texture(Texture& texture);

    private:
        C3D_RenderTarget *target;

        DVLB_s *shader2d_dvlb;
        // DVLB_s *shader3d_dvlb;

        shaderProgram_s program_2d;
        // shaderProgram_s program_3d;

        int proj_uloc_2d;
        // int proj_uloc_3d;

        C3D_Mtx proj_mat;
};

#endif // CITRO3D_GPU_CITRO3D_H
