# PSP

requires = psp

binary = open-tgm.elf

cc = psp-gcc
cxx = psp-g++
link = psp-gcc

common_flags = -D_PSP_FW_VERSION=600
cxxflags = -fno-rtti -fno-exceptions
ldflags = -Wl,-zmax-page-size=128

src_cpp = *.cpp
src_c = *.c

libs = stdc++ pspgum pspgu pspdebug pspdisplay pspge pspctrl pspnet pspnet_apctl

gpu_backend = scegu
gpu_tile_sizes = 10px
gpu_assets = builtin

psp_eboot_title = Open TGM
psp_eboot_icon = NULL
psp_eboot_icon1 = NULL
psp_eboot_unkpng = NULL
psp_eboot_pic1 = NULL
psp_eboot_snd0 = NULL
psp_eboot_psar = NULL
