# Render Makefile

requires = graphics

# Library filename
library = render

src_cpp = render.cpp

# Flags
common_flags = -Wall -Wextra -pedantic-errors
cxx_std = c++20

# Libraries
static_libs = stb canvas freetype
